/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Container } from "react-bootstrap";
import Slider from "react-slick";
import { ChevronUp, ChevronDown } from "react-bootstrap-icons";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Home() {
  function SampleNextArrow(props) {
    const { className, style, onClick } = props;
    return (
      <div className={className} onClick={onClick}>
        <ChevronDown className="icon icon-chevron-down" />
      </div>
    );
  }

  function SamplePrevArrow(props) {
    const { className, style, onClick } = props;
    return (
      <div className={className} onClick={onClick}>
        <ChevronUp className="icon icon-chevron-up" />
      </div>
    );
  }

  const settings = {
    dots: true,
    arrows: true,
    infinite: true,
    autoplay: false,
    autoplaySpeed: 4000,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    draggable: false,
    vertical: true,
    nextArrow: <SampleNextArrow />,
    prevArrow: <SamplePrevArrow />,
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Slider className="intro-slider" {...settings}>
          <div className="intro-slide">
            <div className="intro-slide-inner">
              <img src="/1.jpg" />
              <div className="movie-detail-wrapper">
                <Container>
                  <div className="movie-title">THE MARTIAN</div>
                  <div className="movie-genre-wrapper">
                    <div className="movie-genre">adventure</div>
                    <div className="movie-genre">sci-fi</div>
                    <div className="movie-genre">thriller</div>
                  </div>
                </Container>
              </div>
            </div>
          </div>
          <div className="intro-slide">
            <div className="intro-slide-inner">
              <img src="/2.jpg" />
              <div className="movie-detail-wrapper">
                <Container>
                  <div className="movie-title">THE MARTIAN</div>
                  <div className="movie-genre-wrapper">
                    <div className="movie-genre">adventure</div>
                    <div className="movie-genre">sci-fi</div>
                    <div className="movie-genre">thriller</div>
                  </div>
                </Container>
              </div>
            </div>
          </div>
          <div className="intro-slide">
            <div className="intro-slide-inner">
              <img src="/2.jpg" />
              <div className="movie-detail-wrapper">
                <Container>
                  <div className="movie-title">THE MARTIAN</div>
                  <div className="movie-genre-wrapper">
                    <div className="movie-genre">adventure</div>
                    <div className="movie-genre">sci-fi</div>
                    <div className="movie-genre">thriller</div>
                  </div>
                </Container>
              </div>
            </div>
          </div>
        </Slider>
      </main>
    </>
  );
}
